language: node_js
node_js:
  - 20

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - ng lint
  - ng run-many --all --target=test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
